apiVersion: v1
kind: Namespace
metadata:
  name: ns-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-2
  labels:
    app: nginx2-deployment
  name: nginx2-deployment
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:alpine-slim
        name: nginx
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: ns-2
  name: nginx2-service
spec:
  selector:
    app: nginx-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ns-2
  name: nginx2-ingress
spec:
  rules:
    - host: nginx2.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx2-service
                port:
                  number: 80

